name: Build Unity WebGL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: WebGL Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-

      - name: Setup Unity
        uses: game-ci/unity-actions/setup@v3
        with:
          unityVersion: 6000.0.23f1

      - name: Build WebGL
        uses: game-ci/unity-actions/build@v3
        with:
          targetPlatform: WebGL

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: WebGL-Build
          path: build/WebGL
